### ISSUE TITLE
binding multiple files defined in file

### ISSUE THREAD

**Issue by joshuamschmidt** [divonlan/genozip#10]
Hi @divonlan. 

Currently genozip can bind all files in current directory using `*` wildcard. It would be useful to be able to specify paths of files for binding - either piped from cmd or stored in a file cf tar:

`tar -cvf my_bams.tar -T my_bams.txt`

This would be a handy feature when wanting to bind files that are located within myriad subdirectories.

**Comment by divonlan** [comment]
Thanks @joshuamschmidt for the excellent suggestion. I have added it to my list.

In the mean time, as a work around, you can compress the files individually, and then tar together the compressed files. Something like this might work:

for a in `find .`; do if [ -f $a ] ; then genozip $a ;fi; done

tar cvf mytar.tar `find . -name *.genozip`

**Comment by divonlan** [comment]
@joshuamschmidt this feature is now released. Please see: https://genozip.com/archiving.html
