### ISSUE TITLE
segfault genozip-12.0.8

### ISSUE THREAD

**Issue by joshuamschmidt** [divonlan/genozip#11]
Hi @divonlan, getting segmentation faults after installing genozip-12.0.8 (both conda and github). It occurs after installation on the first invocation with a file (i.e. before registration - without a file the usual 'see manual... etc etc' is output):

This seems specific to 12.0.8 - well at least, I rolled back to 12.0.5 and had no issues.

**Comment by divonlan** [comment]
Hi Joshua,

Thank you for catching and reporting this issue! I have fixed it and released the fix as 12.0.10.

-divon
