### ISSUE TITLE
failed compilation: multiple definition of `dict_id_num_aliases';

### ISSUE THREAD

**Issue by sahwa** [divonlan/genozip#14]
I was trying to compile the latest github release (12.0.34) and it failed after running ``make``. The output is here https://pastebin.com/Fy6z6rpe.

I am running Ubuntu 21.04, gcc 10.3.0 and GNU Make 4.3.

Thank you.

**Comment by divonlan** [comment]
Hi Sam, 

Thanks for reporting this. These issues are now fixed, and it should compile cleanly on gcc 10.

Cheers
-divon
