### ISSUE TITLE
Compression of fastq.gz

### ISSUE THREAD

**Issue by nmuJUN** [divonlan/genozip#19]
Hello,

I have compressed the fastq.gz file using 
`genozip ./test_fastq/test2.R1.fastq.gz ./test_fastq/test2.R2.fastq.gz --pair --reference GRCh37.ref.genozip  -o ./fastq_compress/test.genozip
`
However, when I was uncompressing the test.genozip, the file has become the fastq format although i use the '-z' command
`genounzip  test.genozip --reference /public/user/zj2020/GRch37/GRCh37.ref.genozip`

Is there any problem? Thanks

**Comment by divonlan** [comment]
Thanks for reporting this. A fix for this will be released in the next
release.

In the meantime, a work around is:

genocat test.genozip --component 1 -fo test2.R1.fastq.gz
genocat test.genozip --component 2 -fo test2.R2.fastq.gz

**Comment by divonlan** [comment]
The fix for this issue has now been released as part of release 13.0.7.
