### ISSUE TITLE
Invalid header error - Unexpected compressed_offset value when trying to decrypt genozip

### ISSUE THREAD

**Issue by shepp-hub** [divonlan/genozip#2]
Hi,
I ran into a problem while trying to decrypt a vcf file encrypted and compressed with genozip. The error I keep getting is:
Error: invalid header - expecting compressed_offset to be 64 but found 48. section_type=SEC_DICT

this happens only when the file is password-encrypted and not because the password is wrong. Otherwise, everything works great. I really wish I could fix this issue and start using this software regularly.

Thanks in advance,
Guy

**Comment by divonlan** [comment]
Thanks guy for the feedback and the bug. I will look into it a circle back you.

**Comment by divonlan** [comment]
I could not reproduced this. Possibly fixed as a lot of the relevant code has changed. Please re-open if it recurrs.
