### ISSUE TITLE
Segmentation fault when decompressing a compressed BAM file

### ISSUE THREAD

**Issue by VGalata** [divonlan/genozip#21]
Hello!

First of all, thank you very much for the nice tool!

I wanted to use `genozip` to compress some BAM files. However, when trying to decompress them I get a `Segmentation fault`.

I used the following commands for compression:
```bash
# 1st try
genozip test.bam --threads 5 --best=NO_REF --noisy -i BAM -o test.bam.genozip
# genozip test.bam : Done (1 minute 52 seconds, BAM compression ratio: 2.6)

# 2nd try
genozip test.bam --threads 5 --noisy -i BAM -o test.bam.genozip
# genozip test.bam : Done (1 minute 1 second, BAM compression ratio: 2.1)
```

For decompression, I used
```bash
genounzip test.bam.genozip --noisy --no-PG --output test.2.bam
```

The tool was installed via `conda`: version `13.0.11`, `h7f98852_0`.
The commands were executed in an interactive session on our HPC cluster with 5 CPUs and ca. 130Gb memory being available.
The BAL file used for testing is ca. 1Gb big.

Thank you in advance!

**Comment by divonlan** [comment]
closing for now, as the file decompressed ok on another computer, added to internal bug list to figure out what went wrong here
