### ISSUE TITLE
"Make reference" error in the docs

### ISSUE THREAD

**Issue by jimmybgammyknee** [divonlan/genozip#22]
Just doing some testing on [the make-reference option](https://genozip.readthedocs.io/genozip.html#cmdoption-make-reference)

```
FASTA-specific options (ignored for other file types):

--make-reference  Compresss a FASTA file to be used as a reference in --reference or --REFERENCE.
Example: genozip --make-reference hs37d5.fa.gz

Example: cat *.fa | genozip --input fasta --make-reference --output myref.ref.genozip
```

That example gives a seg fault because no input stream is specified. I think you just missed the `-` after `--make-reference`

```
Example: cat *.fa | genozip --input fasta --make-reference - --output myref.ref.genozip
```

**Comment by divonlan** [comment]
Thanks for the catch! I updated the documentation, and the seg fault will
go away in the next release.
