### ISSUE TITLE
Genozip build failed if I rerun dict_id_gen.sh

### ISSUE THREAD

**Issue by HatakeKakaxi** [divonlan/genozip#26]
There is a file named dict_id_gen.sh in the directory. I ran it by chance and then genozip built failed. Why did it happen? What's the usage of this script?

**Comment by HatakeKakaxi** [comment]
I got it. I should run it like `./dict_id_gen.sh gcc`.

**Comment by divonlan** [comment]
Hi Hatake, that script is used in the development process to auto-generate some source code, it is not normally needed by end users. You can "git stash" to undo changes.
