### ISSUE TITLE
Changes to libbsc source files are not compatible with Apache license

### ISSUE THREAD

**Issue by IlyaGrebnov** [divonlan/genozip#27]
Hi @divonlan,  I notice that you added following changes to libbsc source files.

_
// Please see terms and conditions in the file LICENSE.txt
//
//   WARNING: Genozip is propeitary, not open source software. Modifying the source code is strictly not permitted
//   and subject to penalties specified in the license._

This changes are not compatible with Apache license. Changes to libbsc source files are permitted and encouraged. By using libbsc software your agreed that "any contributions will be under the terms of the license without any terms and conditions".

So please remove warning message and terms + conditions associated with usage of libbsc source code.

**Comment by divonlan** [comment]
Done! Sorry Ilya, this was an unintentional result of an over-promiscuous find/replace.
