### ISSUE TITLE
Exceeding memory allocation when genozipping file from URL

### ISSUE THREAD

**Issue by IdoBar** [divonlan/genozip#7]
Hi,

I'm trying to genozip a `vcf` file directly from URL and I'm running out of memory.
This is my command:
```
 genozip -@ 2 -B 1024 --force ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_raw_GT_with_annot/20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.recalibrated_variants.vcf.gz
```
And this is the error I'm getting from the queue scheduling manager (PBSPro):
```
mem 52479500kb exceeded limit 25165824kb
```
As you can see I tried limiting the block size, but it doesn't have any impact.

Thanks for developing this tool, I would love to include this in my future pipelines (if I could get it running properly).

Ido

**Comment by divonlan** [comment]
Hi Ido, actually that -B value is very large (each thread is to process 1GB of source data) - you can try a smaller -B (you can go as low as 1, but 16-128 are good values).

**Comment by IdoBar** [comment]
Thank you for the quick reply!
I tried with `-B 16`, but still exceeding the memory (though slightly less this time:
```
mem 42293404kb exceeded limit 25165824kb
```
I'm trying again now with `-B 1`.
I must also disclose that when I didn't set the number of threads, the job got killed because it attempted to use >3 threads (while I allowed just 2).
I can increase the memory, but this is only a fairly modest file, how much memory will I need to process an >100GB file?
Are there any documentation or guidelines to the required resources for **genozip** tasks?

Thanks, Ido

**Comment by divonlan** [comment]
Shalom Ido, the amount of memory for -B 16 looks suspeciously high. Let me look into it and get back to you. 
-divon

**Comment by IdoBar** [comment]
Using `-B 1` ran for a few hours, then failed with the following error:
```
Error in file_write:892: failed to write 77174 bytes to 20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.recalibrated_variants.vcf.genozip: Bad file descriptor
```
It may have something to do with the type of storage on that drive, I'm trying it in another location, but so far I think that I'll resort to downloading first and genozipping later.
So far it's been running for 5+ hours (downloading and then genozipping a 27G `vcf` file).
Seems pretty slow, is there any advantage to using multiple threads in the zipping process?

Toda!

**Comment by divonlan** [comment]
Hi Ido,

Ok, I found the issue, fixed it, and released a new release to github and conda (11.0.6). It will take conda about an hour to propogate a new releast through their system.

Details: Genozip allocates a hash table for each field in INFO and FORMAT. It sizes the hash table based on observing the first few thousand lines of the file, and estimating the total expected number of unique values for this field in the entire file by extrapolating the velocity and acceleration of appearance of new values for that field (i.e. first and second derivative), and knowing the file size. The issue was - there was no way to limit the size of the hash tables if you're trying to reduce memory consumption, and this file has a lot of INFO and FORMAT fields and is fairly large. I fixed it to limit the size of the hash table for each field as a function of -B value. In addition, there is a heuristic for detecting fields that have a very small number of possible values. It didn't catch some of the INFO fields in your file that it should have. I fixed that too. Testing your file with -B16, the memory consumption has about halved.

Using multiple threads will speed up compression almost linearly, subject to the disk/network I/O throughput. This is not very useful when compressing from a slow FTP site as the bottleneck will be the download. Not specifying the number of threads will cause Genozip to use the optimal number of the threads for the fastest execution (which is some multiple of the number of cores on the machine). Genozip has been tested to scale up to 100+ concurrent cores.

Thanks again for reporting this issue, and I hope you find Genozip useful

-divon

**Comment by divonlan** [comment]
This is how the compression of this file looks (this is the output of --show-stats):

`VCF file: 20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr22.recalibrated_variants.vcf.gz
Samples: 3202   Variants: 1,927,372   Dictionaries: 93   Vblocks: 11282 x 16 MB  Sections: 1606303
Genozip version: 11.0.5 github
Date compressed: 2021-03-02 19:07:51 ACDT

Sections (sorted by % of genozip file):
NAME              GENOZIP      %      TXT       %   RATIO
FORMAT/PL          7.2 GB  59.3%   59.4 GB  33.9%    8.2X
FORMAT/AD          2.5 GB  20.4%   24.7 GB  14.1%    9.9X
FORMAT/GQ          1.8 GB  15.1%   11.2 GB   6.4%    6.1X
FORMAT/AB        214.9 MB   1.7%    5.7 GB   3.2%   26.9X
FORMAT/GT         94.2 MB   0.8%   17.2 GB   9.8%  187.4X
FORMAT/PID        56.6 MB   0.5%    3.2 GB   1.8%   57.9X
FORMAT/PGT        42.9 MB   0.3%    2.3 GB   1.3%   53.8X
FORMAT/DP         14.1 MB   0.1%   11.4 GB   6.5%  826.4X
INFO/AC_Hnrel      9.5 MB   0.1%   26.9 MB   0.0%    2.8X
QUAL               7.9 MB   0.1%   13.7 MB   0.0%    1.7X
INFO/DP            7.8 MB   0.1%   10.5 MB   0.0%    1.4X
INFO/AF_Anrel      5.7 MB   0.0%   20.4 MB   0.0%    3.6X
INFO/FS            5.5 MB   0.0%    7.3 MB   0.0%    1.3X
INFO/MQRakSum      5.4 MB   0.0%    9.3 MB   0.0%    1.7X
INFO/VQSLOD        5.3 MB   0.0%    9.6 MB   0.0%    1.8X
INFO/BasekSum      5.2 MB   0.0%    9.2 MB   0.0%    1.8X
INFO/ReadkSum      5.1 MB   0.0%    9.0 MB   0.0%    1.7X
INFO/ClipkSum      4.8 MB   0.0%    9.3 MB   0.0%    1.9X
INFO/AF_Enrel      4.8 MB   0.0%   16.9 MB   0.0%    3.5X
INFO/SOR           4.8 MB   0.0%    9.0 MB   0.0%    1.9X
INFO/QD            4.7 MB   0.0%    8.5 MB   0.0%    1.8X
INFO/ExcHet        4.7 MB   0.0%   10.8 MB   0.0%    2.3X
INFO/MLEAF         4.7 MB   0.0%   17.3 MB   0.0%    3.7X
INFO/AF_AFR        4.4 MB   0.0%   11.9 MB   0.0%    2.7X
INFO/AC_Anrel      4.3 MB   0.0%    5.8 MB   0.0%    1.4X
INFO/AF            4.2 MB   0.0%   21.9 MB   0.0%    5.2X
REF+ALT            4.0 MB   0.0%   12.4 MB   0.0%    3.1X
INFO/AC_H_AFR      4.0 MB   0.0%    5.7 MB   0.0%    1.4X
INFO/ExcH_AFR      3.8 MB   0.0%    7.8 MB   0.0%    2.0X
INFO/Inbroeff      3.8 MB   0.0%   10.8 MB   0.0%    2.9X
INFO/AC_Enrel      3.8 MB   0.0%    5.6 MB   0.0%    1.5X
INFO/MLEAC         3.7 MB   0.0%    3.5 MB   0.0%    0.9X
INFO/AC_Het        3.6 MB   0.0%    3.4 MB   0.0%    0.9X
INFO/HWE           3.5 MB   0.0%    6.2 MB   0.0%    1.8X
INFO/AF_SAS        3.4 MB   0.0%    9.2 MB   0.0%    2.7X
INFO/AF_AMR        3.4 MB   0.0%    8.9 MB   0.0%    2.6X
INFO/AF_Snrel      3.3 MB   0.0%    8.8 MB   0.0%    2.6X
INFO/AC_H_SAS      3.3 MB   0.0%    5.4 MB   0.0%    1.6X
INFO/AF_EUR        3.3 MB   0.0%    8.6 MB   0.0%    2.6X
INFO/AC_AFR        3.3 MB   0.0%    3.1 MB   0.0%    0.9X
INFO/AC_H_AMR      3.3 MB   0.0%    5.3 MB   0.0%    1.6X
INFO/AF_EAS        3.2 MB   0.0%    8.5 MB   0.0%    2.6X
INFO/AC_H_EUR      3.2 MB   0.0%    5.4 MB   0.0%    1.7X
INFO/MQ            3.2 MB   0.0%    5.8 MB   0.0%    1.8X
INFO/AC_H_EAS      3.2 MB   0.0%    5.3 MB   0.0%    1.7X
POS                3.1 MB   0.0%   16.5 MB   0.0%    5.3X
INFO/ExcH_AMR      3.1 MB   0.0%    6.2 MB   0.0%    2.0X
INFO/ExcH_SAS      3.0 MB   0.0%    5.9 MB   0.0%    2.0X
INFO/ExcH_EUR      2.9 MB   0.0%    5.7 MB   0.0%    1.9X
INFO/HWE_AFR       2.9 MB   0.0%    5.0 MB   0.0%    1.7X
INFO/ExcH_EAS      2.8 MB   0.0%    5.4 MB   0.0%    1.9X
INFO/AC_SAS        2.8 MB   0.0%    2.8 MB   0.0%    1.0X
INFO/AC_AMR        2.8 MB   0.0%    2.8 MB   0.0%    1.0X
INFO/AC_Snrel      2.8 MB   0.0%    2.8 MB   0.0%    1.0X
INFO/AC_EUR        2.7 MB   0.0%    2.8 MB   0.0%    1.0X
INFO/AC_EAS        2.7 MB   0.0%    2.8 MB   0.0%    1.0X
Other              2.6 MB   0.0%   38.1 GB  21.7% 15174.6X
INFO/HWE_SAS       2.5 MB   0.0%    4.2 MB   0.0%    1.7X
INFO/HWE_AMR       2.5 MB   0.0%    4.1 MB   0.0%    1.7X
INFO/HWE_EUR       2.4 MB   0.0%    4.1 MB   0.0%    1.7X
INFO/AC_Hom        2.4 MB   0.0%    2.8 MB   0.0%    1.2X
INFO/ME            2.4 MB   0.0%    4.5 MB   0.0%    1.9X
INFO/HWE_EAS       2.4 MB   0.0%    4.0 MB   0.0%    1.7X
INFO               1.5 MB   0.0%    1.6 GB   0.9% 1105.8X
INFO/AC            1.5 MB   0.0%    3.5 MB   0.0%    2.4X
FORMAT             1.3 MB   0.0%   37.9 MB   0.0%   28.4X
INFO/culprit       1.3 MB   0.0%    5.5 MB   0.0%    4.2X
INFO/AN_Anrel      1.2 MB   0.0%   12.8 MB   0.0%   10.4X
INFO/AN            1.2 MB   0.0%    7.4 MB   0.0%    6.1X
INFO/AN_Enrel      1.2 MB   0.0%   14.4 MB   0.0%   12.3X
INFO/AN_AFR     1010.2 KB   0.0%    7.3 MB   0.0%    7.4X
INFO/AN_SAS      955.8 KB   0.0%    7.3 MB   0.0%    7.8X
INFO/AN_EUR      953.6 KB   0.0%    7.3 MB   0.0%    7.9X
INFO/AN_EAS      949.4 KB   0.0%    7.3 MB   0.0%    7.9X
INFO/AN_AMR      944.0 KB   0.0%    5.5 MB   0.0%    6.0X
INFO/AN_Snrel    941.2 KB   0.0%    5.5 MB   0.0%    6.0X
FILTER           884.0 KB   0.0%   15.0 MB   0.0%   17.4X
INFO/MQ0         640.4 KB   0.0%    1.8 MB   0.0%    2.9X
CHROM                46 B   0.0%   11.0 MB   0.0% 251396.3X
ID                   42 B   0.0%    3.7 MB   0.0% 91779.6X
TOTAL vs BGZF     12.2 GB 100.0%   26.0 GB 100.0%    2.1X
TOTAL vs TXT      12.2 GB 100.0%  175.3 GB 100.0%   14.4X
`

**Comment by IdoBar** [comment]
Thanks for the prompt and very detailed response!
I'll update the package on conda and will give it another go.
Cheers, Ido
