### ISSUE TITLE
genozip --make-reference not working on .fna file

### ISSUE THREAD

**Issue by IdoBar** [divonlan/genozip#8]
genozip complains and fails when provided a reference file with a suffix other than '.fa' or '.fasta'
```
>genozip --make-reference $GENOME.fna

genozip: --make-reference can only be used with FASTA files
```
While this works:
```
>ln -s $GENOME.fna $GENOME.fa
>genozip --make-reference $GENOME.fa
genozip A_rabiei_me14.fa : Writing hash table (this can take several minutes)...
```
A better way would be to actually check the content of the file and validate as fasta.

**Comment by divonlan** [comment]
Thanks Ido for reporting an the excellent suggestion.

**Comment by divonlan** [comment]
Update: @IdoBar : --make-reference now works on .fna files as well.
