### ISSUE TITLE
genozip --register aborted (core dumped)

### ISSUE THREAD

**Issue by Chipcui** [divonlan/genozip#9]
genozip: Error accessing the Internet:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:49 --:--:--     0
Aborted (core dumped)

**Comment by divonlan** [comment]
Hi Xiaobo, I have heard reports that registration is failing in mainland China, it might because it goes through Google servers. Please kindly email me to divon@genozip.com with your full name, organization name and email address and I will register you manually. Thanks!
